### ISSUE TITLE
Provenance for Whisper

### ISSUE THREAD

**Issue by Veldhoen** [beeldengeluid/whisper-asr-worker#81]

**Comment by mwigham** [comment]
Example of the current provenance output is [here](https://eu-west-1.console.aws.amazon.com/s3/object/beng-daan-asr?region=eu-west-1&bucketType=general&prefix=test_items/2101608040029197331__VOORDEVUISTWE-HRE000052FC/provenance.json). Note the list format so provenance can be appended per step.

I haven't filled in software version at present as we had a problem trying to get that information while in a Docker container. So if you have a solution for this then it is very welcome!
